# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by vendor/alcatel/cocktail/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES += \
    vendor/alcatel/cocktail/bcmdhd.cal:/system/etc/wifi/bcmdhd.cal
    vendor/alcatel/cocktail/proprietary/bcm4330.hcd:/system/etc/firmware/bcm4330.hcd \
    vendor/alcatel/cocktail/proprietary/bcm4330.ko:/system/lib/modules/bcm4330.ko \
    vendor/alcatel/cocktail/proprietary/camera.msm7630_surf.so:/system/lib/hw/camera.cocktail.so \
    vendor/alcatel/cocktail/proprietary/camera.msm7630_surf.so:/system/lib/hw/camera.msm7630_surf.so \
    vendor/alcatel/cocktail/proprietary/cfg80211.ko:/system/lib/modules/cfg80211.ko \
    vendor/alcatel/cocktail/proprietary/compat.ko:/system/lib/modules/compat.ko \
    vendor/alcatel/cocktail/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_command_control.fw:/system/etc/firmware/vidc_720p_command_control.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_h263_dec_mc.fw:/system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_h264_dec_mc.fw:/system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_h264_enc_mc.fw:/system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_mp4_dec_mc.fw:/system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_mp4_enc_mc.fw:/system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/alcatel/cocktail/proprietary/firmware/vidc_720p_vc1_dec_mc.fw:/system/etc/firmware/vidc_720p_vc1_dec_mc.fw
    vendor/alcatel/cocktail/proprietary/fw_bcmdhd.bin:/system/etc/firmware/fw_bcmdhd.bin \
    vendor/alcatel/cocktail/proprietary/fw_bcmdhd_apsta.bin:/system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/alcatel/cocktail/proprietary/fw_bcmdhd_p2p.bin:/system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/alcatel/cocktail/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so
    vendor/alcatel/cocktail/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/alcatel/cocktail/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so
    vendor/alcatel/cocktail/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/alcatel/cocktail/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/alcatel/cocktail/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/alcatel/cocktail/proprietary/libchromatix_ov5647_preview.so:/system/lib/libchromatix_ov5647_preview.so
    vendor/alcatel/cocktail/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/alcatel/cocktail/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/alcatel/cocktail/proprietary/libdsutils.so:/system/lib/libdsutils.so \
    vendor/alcatel/cocktail/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/alcatel/cocktail/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/alcatel/cocktail/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/alcatel/cocktail/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/alcatel/cocktail/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/alcatel/cocktail/proprietary/libidl.so:/system/lib/libidl.so \
    vendor/alcatel/cocktail/proprietary/libmllite.so:/system/lib/libmllite.so \
    vendor/alcatel/cocktail/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/alcatel/cocktail/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/alcatel/cocktail/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/alcatel/cocktail/proprietary/libmpl.so:/system/lib/libmpl.so \
    vendor/alcatel/cocktail/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/alcatel/cocktail/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/alcatel/cocktail/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/alcatel/cocktail/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/alcatel/cocktail/proprietary/libqdi.so:/system/lib/libqdi.so \
    vendor/alcatel/cocktail/proprietary/libqdp.so:/system/lib/libqdp.so \
    vendor/alcatel/cocktail/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/alcatel/cocktail/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/alcatel/cocktail/proprietary/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
    vendor/alcatel/cocktail/proprietary/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/alcatel/cocktail/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so
    vendor/alcatel/cocktail/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/alcatel/cocktail/proprietary/lights.msm7630_surf.so:/system/lib/hw/lights.cocktail.so \
    vendor/alcatel/cocktail/proprietary/lights.msm7630_surf.so:/system/lib/hw/lights.msm7630_surf \
    vendor/alcatel/cocktail/proprietary/netmgrd:/system/bin/netmgrd
    vendor/alcatel/cocktail/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/alcatel/cocktail/proprietary/qmiproxy:/system/bin/qmiproxy \
    vendor/alcatel/cocktail/proprietary/qmuxd:/system/bin/qmuxd \
    vendor/alcatel/cocktail/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/alcatel/cocktail/proprietary/sensors.cocktail.so:/system/lib/hw/sensors.cocktail.so \
    vendor/alcatel/cocktail/proprietary/sensors.qcom.so:/system/lib/hw/sensors.cocktail.so
    vendor/alcatel/cocktail/proprietary/sensors.qcom.so:/system/lib/hw/sensors.qcom.so
    vendor/alcatel/cocktail/proprietary/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/alcatel/cocktail/proprietary/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
#   vendor/alcatel/cocktail/proprietary/libril.so:/system/lib/libril.so \      
#   vendor/alcatel/cocktail/proprietary/rild:/system/bin/rild \

